// Mock data for events with consistent IDs
export const EVENTS = [
  {
    id: "summer-beats-festival",
    name: "Summer Beats Festival",
    dj: "DJ Pulse",
    date: new Date("2025-06-15"),
    time: "4:00 PM - 11:00 PM",
    venue: "Skyline Venue, Downtown",
    address: "123 Main Street, Downtown",
    price: 45,
    image: "/summer-festival.jpg",
    genre: "Electronic",
    description:
      "Join us for the hottest electronic music festival of the summer! DJ Pulse will be headlining with support from other amazing electronic artists.",
    capacity: 2000,
    ticketsRemaining: 450,
  },
  {
    id: "neon-nights",
    name: "Neon Nights",
    dj: "DJ Nova",
    date: new Date("2025-07-03"),
    time: "10:00 PM - 4:00 AM",
    venue: "The Warehouse, East Side",
    address: "456 Industrial Ave, East Side",
    price: 35,
    image: "/neon-nights.jpg",
    genre: "Electronic",
    description: "Step into a world of neon lights and electronic beats at this immersive nightclub experience.",
    capacity: 800,
    ticketsRemaining: 320,
  },
  {
    id: "retro-remix",
    name: "Retro Remix",
    dj: "DJ Throwback",
    date: new Date("2025-07-22"),
    time: "9:00 PM - 2:00 AM",
    venue: "Classic Lounge, West End",
    address: "789 Vintage Blvd, West End",
    price: 40,
    image: "/retro-remix.jpg",
    genre: "Pop",
    description: "Travel back in time with DJ Throwback as they spin the greatest hits from the 70s, 80s, and 90s.",
    capacity: 500,
    ticketsRemaining: 210,
  },
  {
    id: "latin-fiesta",
    name: "Latin Fiesta",
    dj: "DJ Ritmo",
    date: new Date("2025-09-02"),
    time: "8:00 PM - 1:00 AM",
    venue: "Salsa Club, East End",
    address: "321 Rhythm Street, East End",
    price: 40,
    image: "/latin-fiesta.jpg",
    genre: "Latin",
    description: "Experience the passion and energy of Latin music at this vibrant fiesta!",
    capacity: 400,
    ticketsRemaining: 180,
  },
  {
    id: "edm-explosion",
    name: "EDM Explosion",
    dj: "DJ Spark",
    date: new Date("2025-09-28"),
    time: "7:00 PM - 2:00 AM",
    venue: "Mega Arena, Downtown",
    address: "987 Electric Avenue, Downtown",
    price: 50,
    image: "/edm-explosion.jpg",
    genre: "Electronic",
    description:
      "The biggest EDM event of the year featuring cutting-edge visuals, pyrotechnics, and the best electronic dance music.",
    capacity: 5000,
    ticketsRemaining: 1200,
  },
  {
    id: "techno-tuesday",
    name: "Techno Tuesday",
    dj: "DJ Circuit",
    date: new Date("2025-10-15"),
    time: "9:00 PM - 3:00 AM",
    venue: "Underground Club, Downtown",
    address: "555 Basement Ave, Downtown",
    price: 30,
    image: "/techno-tuesday.jpg",
    genre: "Electronic",
    description: "Weekly techno night featuring the best underground DJs and cutting-edge electronic music.",
    capacity: 300,
    ticketsRemaining: 150,
  },
  {
    id: "house-party",
    name: "House Party",
    dj: "DJ Groove",
    date: new Date("2025-11-05"),
    time: "10:00 PM - 4:00 AM",
    venue: "The Loft, West Side",
    address: "789 Rhythm Street, West Side",
    price: 35,
    image: "/house-party.jpg",
    genre: "House",
    description: "A night of deep house and soulful beats in an intimate venue with amazing sound.",
    capacity: 250,
    ticketsRemaining: 100,
  },
  {
    id: "winter-wonderland",
    name: "Winter Wonderland",
    dj: "DJ Frost",
    date: new Date("2025-12-20"),
    time: "8:00 PM - 2:00 AM",
    venue: "Ice Palace, North End",
    address: "123 Snowflake Drive, North End",
    price: 55,
    image: "/winter-wonderland.jpg",
    genre: "Electronic",
    description: "A magical winter-themed electronic music event with stunning visuals and top DJs.",
    capacity: 1500,
    ticketsRemaining: 800,
  },
]

// Mock song data for each event
export const MOCK_SONGS = {
  "summer-beats-festival": [
    {
      id: "summer-song-1",
      title: "Blinding Lights",
      artist: "The Weeknd",
      tokens: 145,
      bidders: 3,
      trending: "up",
    },
    {
      id: "summer-song-2",
      title: "Don't Start Now",
      artist: "Dua Lipa",
      tokens: 132,
      bidders: 2,
      trending: "down",
    },
  ],
  "neon-nights": [
    {
      id: "neon-song-1",
      title: "Midnight City",
      artist: "M83",
      tokens: 120,
      bidders: 4,
      trending: "up",
    },
    {
      id: "neon-song-2",
      title: "Tondo",
      artist: "Disclosure",
      tokens: 95,
      bidders: 2,
      trending: "up",
    },
  ],
  "retro-remix": [
    {
      id: "retro-song-1",
      title: "Stayin' Alive",
      artist: "Bee Gees",
      tokens: 110,
      bidders: 5,
      trending: "up",
    },
    {
      id: "retro-song-2",
      title: "Billie Jean",
      artist: "Michael Jackson",
      tokens: 105,
      bidders: 3,
      trending: "down",
    },
  ],
  "latin-fiesta": [
    {
      id: "latin-song-1",
      title: "Despacito",
      artist: "Luis Fonsi ft. Daddy Yankee",
      tokens: 130,
      bidders: 6,
      trending: "up",
    },
    {
      id: "latin-song-2",
      title: "Vivir Mi Vida",
      artist: "Marc Anthony",
      tokens: 85,
      bidders: 2,
      trending: "down",
    },
  ],
  "edm-explosion": [
    {
      id: "edm-song-1",
      title: "Levels",
      artist: "Avicii",
      tokens: 160,
      bidders: 7,
      trending: "up",
    },
    {
      id: "edm-song-2",
      title: "Strobe",
      artist: "Deadmau5",
      tokens: 140,
      bidders: 4,
      trending: "up",
    },
  ],
  "techno-tuesday": [
    {
      id: "techno-song-1",
      title: "Opus",
      artist: "Eric Prydz",
      tokens: 90,
      bidders: 3,
      trending: "up",
    },
    {
      id: "techno-song-2",
      title: "Adagio for Strings",
      artist: "Tiësto",
      tokens: 85,
      bidders: 2,
      trending: "down",
    },
  ],
  "house-party": [
    {
      id: "house-song-1",
      title: "Music Sounds Better With You",
      artist: "Stardust",
      tokens: 75,
      bidders: 3,
      trending: "up",
    },
    {
      id: "house-song-2",
      title: "Show Me Love",
      artist: "Robin S",
      tokens: 70,
      bidders: 2,
      trending: "down",
    },
  ],
  "winter-wonderland": [
    {
      id: "winter-song-1",
      title: "Snowfall",
      artist: "Eskimo",
      tokens: 65,
      bidders: 2,
      trending: "up",
    },
    {
      id: "winter-song-2",
      title: "Cold Heart",
      artist: "Elton John & Dua Lipa",
      tokens: 60,
      bidders: 1,
      trending: "down",
    },
  ],
}
